name: NPM Audit

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        default: ''
      audit_level:
        type: string
        default: moderate
      issue_assignees:
        type: string
        default: robjstanley
      issue_labels:
        type: string
        default: vulnerability,npm
    secrets:
      AUDIT_ACTION_PAT:
        required: true

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine Node.js version
        id: node_version
        run: |
          if [ -n "${{ inputs.node_version }}" ]; then
            echo "Using node version from input: ${{ inputs.node_version }}"
            echo "version=${{ inputs.node_version }}" >> $GITHUB_OUTPUT
          elif [ -f ".nvmrc" ]; then
            nvm_version=$(cat .nvmrc)
            echo "Using node version from .nvmrc: $nvm_version"
            echo "version=$nvm_version" >> $GITHUB_OUTPUT
          else
            echo "No node version provided and .nvmrc not found. Exiting."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node_version.outputs.version }}

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit and create issue
        uses: oke-py/npm-audit-action@v3
        with:
          audit_level: ${{ inputs.audit_level }}
          github_token: ${{ secrets.AUDIT_ACTION_PAT }}
          issue_assignees: ${{ inputs.issue_assignees }}
          issue_labels: ${{ inputs.issue_labels }}
          dedupe_issues: true
